// -----------------------------------------------------------------------
// <copyright file="GoBufio.cs" company="Ziad">
//  Copyright 2016 Ziad
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// </copyright>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;

namespace Ngo.Runtime
{
    /// <summary>
    /// Runtime support for Go's bufio package.
    /// </summary>
    public static class GoBufio
    {
        public static GoScanner NewScanner(IGoReader r)
        {
            return new GoScanner(r);
        }

        public static GoBufferedReader NewReader(IGoReader r)
        {
            return new GoBufferedReader(r);
        }

        public static GoBufferedWriter NewWriter(IGoWriter w)
        {
            return new GoBufferedWriter(w);
        }
    }

    /// <summary>
    /// bufio.Scanner — reads input token by token (default: lines).
    /// </summary>
    public sealed class GoScanner
    {
        private readonly IGoReader _reader;
        private readonly byte[] _buf;
        private int _bufLen;
        private int _bufPos;
        private string _token;
        private bool _done;

        public GoScanner(IGoReader reader)
        {
            _reader = reader;
            _buf = new byte[4096];
            _bufLen = 0;
            _bufPos = 0;
            _token = "";
            _done = false;
        }

        /// <summary>
        /// Scan advances the Scanner to the next token (default: line).
        /// Returns true if a token is available.
        /// </summary>
        public bool Scan()
        {
            if (_done)
                return false;

            var line = new List<byte>();
            while (true)
            {
                if (_bufPos >= _bufLen)
                {
                    var slice = new Slice<byte>(_buf);
                    var (n, err) = _reader.Read(slice);
                    if (n == 0)
                    {
                        _done = true;
                        if (line.Count > 0)
                        {
                            _token = Encoding.UTF8.GetString(line.ToArray());
                            return true;
                        }
                        return false;
                    }
                    _bufLen = n;
                    _bufPos = 0;
                }

                byte b = _buf[_bufPos++];
                if (b == (byte)'\n')
                {
                    // Strip trailing \r if present
                    if (line.Count > 0 && line[line.Count - 1] == (byte)'\r')
                        line.RemoveAt(line.Count - 1);
                    _token = Encoding.UTF8.GetString(line.ToArray());
                    return true;
                }
                line.Add(b);
            }
        }

        /// <summary>Returns the most recent token generated by Scan.</summary>
        public string Text()
        {
            return _token;
        }
    }

    /// <summary>
    /// bufio.Reader — buffered reader wrapping an io.Reader.
    /// Implements IGoReader.
    /// </summary>
    public sealed class GoBufferedReader : IGoReader
    {
        private readonly IGoReader _reader;
        private readonly byte[] _buf;
        private int _bufLen;
        private int _bufPos;

        public GoBufferedReader(IGoReader reader, int bufSize = 4096)
        {
            _reader = reader;
            _buf = new byte[bufSize];
            _bufLen = 0;
            _bufPos = 0;
        }

        public (int, string) Read(Slice<byte> p)
        {
            if (_bufPos >= _bufLen)
            {
                var slice = new Slice<byte>(_buf);
                var (n, err) = _reader.Read(slice);
                if (n == 0)
                    return (0, err);
                _bufLen = n;
                _bufPos = 0;
            }

            int count = Math.Min(p.Len, _bufLen - _bufPos);
            for (int i = 0; i < count; i++)
                p[i] = _buf[_bufPos + i];
            _bufPos += count;
            return (count, "");
        }

        /// <summary>
        /// ReadString reads until the first occurrence of delim and returns
        /// the data including the delimiter.
        /// </summary>
        public (string, string) ReadString(byte delim)
        {
            var result = new List<byte>();
            while (true)
            {
                if (_bufPos >= _bufLen)
                {
                    var slice = new Slice<byte>(_buf);
                    var (n, err) = _reader.Read(slice);
                    if (n == 0)
                    {
                        if (result.Count > 0)
                            return (Encoding.UTF8.GetString(result.ToArray()), err);
                        return ("", err);
                    }
                    _bufLen = n;
                    _bufPos = 0;
                }

                byte b = _buf[_bufPos++];
                result.Add(b);
                if (b == delim)
                    return (Encoding.UTF8.GetString(result.ToArray()), "");
            }
        }
    }

    /// <summary>
    /// bufio.Writer — buffered writer wrapping an io.Writer.
    /// Implements IGoWriter.
    /// </summary>
    public sealed class GoBufferedWriter : IGoWriter
    {
        private readonly IGoWriter _writer;
        private readonly byte[] _buf;
        private int _bufLen;

        public GoBufferedWriter(IGoWriter writer, int bufSize = 4096)
        {
            _writer = writer;
            _buf = new byte[bufSize];
            _bufLen = 0;
        }

        public (int, string) Write(Slice<byte> p)
        {
            int written = 0;
            for (int i = 0; i < p.Len; i++)
            {
                _buf[_bufLen++] = p[i];
                written++;
                if (_bufLen >= _buf.Length)
                {
                    var (_, err) = FlushInternal();
                    if (err != "")
                        return (written, err);
                }
            }
            return (written, "");
        }

        /// <summary>Flush writes buffered data to the underlying Writer.</summary>
        public string Flush()
        {
            var (_, err) = FlushInternal();
            return err;
        }

        private (int, string) FlushInternal()
        {
            if (_bufLen == 0)
                return (0, "");
            var slice = new Slice<byte>(_buf, 0, _bufLen);
            var result = _writer.Write(slice);
            _bufLen = 0;
            return result;
        }
    }
}
