<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <GarbageCollectionAdaptationMode>0</GarbageCollectionAdaptationMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ngo.Compiler\Ngo.Compiler.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="packages.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="stdlib.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
