// -----------------------------------------------------------------------
// <copyright file="CgoPseudoNames.cs" company="Ziad">
//  Copyright 2016 Ziad
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// </copyright>
// -----------------------------------------------------------------------

using System.Collections.Generic;

namespace Ngo.Compiler.Cgo
{
    /// <summary>
    /// The fixed set of Go-side cgo helpers that appear as <c>C.&lt;name&gt;</c>
    /// in Go source but are not C symbols: they are generated by the Go
    /// cgo toolchain and implemented on the Go side. Attempting to
    /// <c>sizeof</c> or link them in a C probe yields <c>undeclared here</c>
    /// errors. The list is defined by the Go cgo specification (see
    /// <c>cmd/cgo</c> documentation) and is stable across Go versions.
    /// </summary>
    public static class CgoPseudoNames
    {
        private static readonly HashSet<string> PseudoNames = new(System.StringComparer.Ordinal)
        {
            "CString",
            "CBytes",
            "GoString",
            "GoStringN",
            "GoBytes",
        };

        /// <summary>
        /// Returns <c>true</c> when <paramref name="name"/> is one of the
        /// Go-side cgo helpers and must not be forwarded to C tooling.
        /// </summary>
        public static bool IsPseudoName(string name)
        {
            return PseudoNames.Contains(name);
        }
    }
}
